contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #popgennf channel"
    url: https://nfcore.slack.com/channels/popgennf
    about: Discussion about the nf-core/popgennf pipeline
